cy-dev:
	yarn cypress open

cy:
	yarn cypress run

ab:
	ab -kc 10 -t 60 http://localhost:8080/
	ab -kc 10 -t 60 http://localhost:8080/blog/
	ab -kc 10 -t 60 http://localhost:8080/blog/category/health-and-food/
	ab -kc 10 -t 60 http://localhost:8080/blog/the-best-juices-for-a-child/
	ab -kc 10 -t 60 http://localhost:8080/shop/
	ab -kc 10 -t 60 http://localhost:8080/shop/category/electronics/
	ab -kc 10 -t 60 http://localhost:8080/shop/samsung-galaxy-s10-128-gb/
