package template

var AllData = map[string][]byte{
	"cached-block-3.html": VarCachedBlock_3HtmlFile,
	"cached-block-1.html": VarCachedBlock_1HtmlFile,
	"blog-category.html":  VarBlogCategoryHtmlFile,
	"footer.html":         VarFooterHtmlFile,
	"styles.css":          VarStylesCssFile,
	"header.html":         VarHeaderHtmlFile,
	"blog.html":           VarBlogHtmlFile,
	"shop-product.html":   VarShopProductHtmlFile,
	"index.html":          VarIndexHtmlFile,
	"robots.txt":          VarRobotsTxtFile,
	"page.html":           VarPageHtmlFile,
	"cached-block-2.html": VarCachedBlock_2HtmlFile,
	"404.html":            Var404HtmlFile,
	"shop.html":           VarShopHtmlFile,
	"shop-category.html":  VarShopCategoryHtmlFile,
	"blog-post.html":      VarBlogPostHtmlFile,
	"scripts.js":          VarScriptsJsFile,
	"sidebar-left.html":   VarSidebarLeftHtmlFile,
	"cached-block-4.html": VarCachedBlock_4HtmlFile,
	"sidebar-right.html":  VarSidebarRightHtmlFile,
	"cached-block-5.html": VarCachedBlock_5HtmlFile,
}
