package template

var AllData = map[string][]byte{
	"blog.html":                  VarBlogHtmlFile,
	"shop.html":                  VarShopHtmlFile,
	"shop-product.html":          VarShopProductHtmlFile,
	"maintenance.html":           VarMaintenanceHtmlFile,
	"footer.html":                VarFooterHtmlFile,
	"header.html":                VarHeaderHtmlFile,
	"sidebar-right.html":         VarSidebarRightHtmlFile,
	"index.html":                 VarIndexHtmlFile,
	"email-new-order-admin.html": VarEmailNewOrderAdminHtmlFile,
	"cached-block-2.html":        VarCachedBlock_2HtmlFile,
	"robots.txt":                 VarRobotsTxtFile,
	"cached-block-4.html":        VarCachedBlock_4HtmlFile,
	"cached-block-5.html":        VarCachedBlock_5HtmlFile,
	"scripts.js":                 VarScriptsJsFile,
	"page.html":                  VarPageHtmlFile,
	"blog-category.html":         VarBlogCategoryHtmlFile,
	"cached-block-3.html":        VarCachedBlock_3HtmlFile,
	"404.html":                   Var404HtmlFile,
	"blog-post.html":             VarBlogPostHtmlFile,
	"shop-category.html":         VarShopCategoryHtmlFile,
	"sidebar-left.html":          VarSidebarLeftHtmlFile,
	"styles.css":                 VarStylesCssFile,
	"email-new-order-user.html":  VarEmailNewOrderUserHtmlFile,
	"cached-block-1.html":        VarCachedBlock_1HtmlFile,
}
